# Generated by Django 4.1.7 on 2023-03-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=None),
        ),
    ]
