# Generated by Django 4.1.7 on 2023-03-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_date_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
