# Generated by Django 4.1.7 on 2023-03-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_event_end_time_event_start_date_event_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(default=None)),
                ('start_time', models.TimeField(default=None)),
                ('end_time', models.TimeField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
