# Generated by Django 4.1.7 on 2023-03-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_meeting1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting1',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='meeting1',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='meeting1',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='meeting1',
            name='title',
        ),
        migrations.AddField(
            model_name='meeting1',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting1',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
